### PR TITLE
add timsnyder and v3.2.1

### PR DESCRIPTION
**Pull request by timsnyder**
Checklist
* [X] Used a fork of the feedstock to propose changes
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Closes: #9 
Closes: #10 
Closes: #11 
Closes: #12 

I think since Python 2.7 has officially been dropped that a rerender on #12 would have passed but I also wanted to add myself as a maintainer of this recipe since my team needs it.

### CODE REVIEW

**Comment by timsnyder** [comment]
Looks like [the license file was packaged](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=133994&view=logs&j=1bf226d3-0e2f-52d8-fa93-7d9e633347b3&t=ec8d466d-e3b4-5115-4f06-222398f91e6c&l=519)

Can someone from @conda-forge/core help me get this merged?  I added myself as a maintainer so that I can help keep this moving forward in the future.

**Comment by beckermr** [comment]
you need to bump @conda-forge/django-cors-headers

**Comment by timsnyder** [comment]
@beckermr , given that there is a pileup of autotick PR's and the fact that @conda-forge/django-cors-headers hasn't been active and @CJ-Wright's [comment on #12](https://github.com/conda-forge/django-cors-headers-feedstock/pull/12#issuecomment-597388169), I jumped a step and pinged core straight away.  

You're right though.  I should have pinged the feedstock maintainers first.

**Comment by beckermr** [comment]
Ahhh sorry! Yep, you are right. Very very happy to have you on board to take this over! Thank you!

**Comment by CJ-Wright** [comment]
you might consider adding the bot automerge functionality on this feedstock to help with all the version bumps https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-admin-please-add-bot-automerge

**Pull request merged**
